import { MetricsProvider } from '@/context/MetricsContext'; // adjust the path

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <MetricsProvider>
      {children}
    </MetricsProvider>
    // <html lang="en">
      // <body>{children}</body>
    // </html>
  )
}
