import "./globals.css";
import { UserProvider } from "@/context/UserContext";
import AppWrapper from "@/components/AppWrapper";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
        <body>
            <UserProvider>
              <AppWrapper>{children}</AppWrapper>
            </UserProvider>
      </body>
    </html>
  )
}
