import "../globals.css";
import { PostProvider } from "@/context/PostContext";
import { UserConnectionsProvider } from "@/context/UserConnectionsContext";
import { ConversationsProvider } from "@/context/ConversationsContext";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <PostProvider>

<UserConnectionsProvider>
                <ConversationsProvider>
      {children}

      </ConversationsProvider>
              </UserConnectionsProvider>
    </PostProvider>
  )
}
