import { Toaster } from "react-hot-toast";
import "../globals.css";
import "react-datepicker/dist/react-datepicker.css";
import Head from "next/head";

export const metadata = {
  title: "Netsoo",
  description: "Generated by TechXen",
};

export default function RootLayout({ children }) {
  return (
    <>
    <Head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="true" />
        <link
          href="https://fonts.googleapis.com/css2?family=Onest:wght@100..900&display=swap"
          rel="stylesheet"
        />
      </Head>
      
        <div
          className="bg-[url('/client/landingBg1.svg')] bg-cover bg-center  bg-no-repeat"
        >
          {children}
        </div>
        <Toaster
          position="bottom-center"
          reverseOrder={false}
          gutter={8}
          toastOptions={{
            duration: 5000,
            removeDelay: 1000,
            style: {
              background: "#171717",
              color: "#fff",
              border: "2px solid #FFFFFF30",
              borderRadius: "12px",
              width: "420px",
              padding: "16px",
            },
            success: {
              duration: 3000,
              iconTheme: {
                primary: "#30AD81",
                secondary: "#fff",
              },
            },
          }}
        />
    </>
  );
}
